import {
  Wifi,
  Waves,
  Dumbbell,
  ParkingCircle,
  Wind,
  Tv,
  Refrigerator,
  Coffee,
  UtensilsCrossed,
  Users,
  Sparkles,
  ShieldCheck,
  Snowflake,
  Bath,
  Briefcase,
  Car,
  Cigarette,
  Dog,
  Flower2,
  Gamepad2,
  HeartPulse,
  Luggage,
  PawPrint,
  Phone,
  Shirt,
  ShowerHead,
  Sun,
  Tag,
  Tv2,
  Umbrella,
  Wine,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  wifi: Wifi,
  waves: Waves,
  dumbbell: Dumbbell,
  "parking-circle": ParkingCircle,
  parking: ParkingCircle,
  wind: Wind,
  tv: Tv,
  television: Tv2,
  refrigerator: Refrigerator,
  fridge: Refrigerator,
  coffee: Coffee,
  "utensils-crossed": UtensilsCrossed,
  restaurant: UtensilsCrossed,
  users: Users,
  sparkles: Sparkles,
  housekeeping: Sparkles,
  "shield-check": ShieldCheck,
  security: ShieldCheck,
  snowflake: Snowflake,
  ac: Snowflake,
  bath: Bath,
  bathtub: Bath,
  briefcase: Briefcase,
  business: Briefcase,
  car: Car,
  cigarette: Cigarette,
  smoking: Cigarette,
  dog: Dog,
  pet: PawPrint,
  flower: Flower2,
  garden: Flower2,
  games: Gamepad2,
  fitness: HeartPulse,
  gym: Dumbbell,
  luggage: Luggage,
  phone: Phone,
  laundry: Shirt,
  shower: ShowerHead,
  sun: Sun,
  pool: Waves,
  tag: Tag,
  umbrella: Umbrella,
  wine: Wine,
  bar: Wine,
};

export function resolveIcon(name?: string): LucideIcon {
  if (!name) return Sparkles;
  return ICON_MAP[name.toLowerCase().trim()] ?? Sparkles;
}

export const ICON_OPTIONS: { value: string; label: string }[] = [
  { value: "wifi", label: "Wi-Fi" },
  { value: "waves", label: "Swimming Pool" },
  { value: "dumbbell", label: "Gym / Fitness" },
  { value: "parking-circle", label: "Parking" },
  { value: "wind", label: "Air Conditioning" },
  { value: "tv", label: "Television" },
  { value: "television", label: "Entertainment" },
  { value: "refrigerator", label: "Mini Fridge" },
  { value: "coffee", label: "Tea / Coffee Maker" },
  { value: "utensils-crossed", label: "Dining" },
  { value: "users", label: "Private Dining / Group" },
  { value: "sparkles", label: "Housekeeping" },
  { value: "shield-check", label: "Security" },
  { value: "snowflake", label: "Cooling" },
  { value: "bath", label: "Bathtub" },
  { value: "briefcase", label: "Business Centre" },
  { value: "car", label: "Valet / Car Service" },
  { value: "cigarette", label: "Smoking Area" },
  { value: "dog", label: "Dog Friendly" },
  { value: "pet", label: "Pet Friendly" },
  { value: "flower", label: "Garden" },
  { value: "games", label: "Game Room" },
  { value: "fitness", label: "Wellness / Spa" },
  { value: "luggage", label: "Luggage Storage" },
  { value: "phone", label: "Phone / Reception" },
  { value: "laundry", label: "Laundry Service" },
  { value: "shower", label: "Shower" },
  { value: "sun", label: "Sun Deck / Terrace" },
  { value: "tag", label: "Offers" },
  { value: "umbrella", label: "Beachside / Umbrella" },
  { value: "wine", label: "Bar / Lounge" },
];
